# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ahmet yalcinkaya
tagline: "London-based iOS Contractor"
picture: ahmetws.jpg #keep a 100x100 image inside images folder.
email: hello@email.com
description: > # this means to ignore newlines until "baseurl:"
  ahmetws website
baseurl: "/" # the subpath of your site, e.g. /blog
twitter-url: "https://twitter.com/theswiftist"
linkedin-url: "https://www.linkedin.com/in/ayalcinkaya"
github-url: "https://github.com/ahmetws"
url: "http://ahmet.ws/" # the base hostname & protocol for your site
brand-color: '#4b6584'
permalink: ':title/'

# Footer
credits: webjeda #credits on the footer
version: 1.0

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

sass:
  style: compressed
  
analytics: UA-137118398-1

include: []



#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


gems: [jekyll-paginate, jekyll-seo-tag]